name: 365project
favicon: null
layout_spectrum: 0.24664
typography_spectrum: 0.89264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f262c'
    - '#e9eaec'
    - '#b3c3d4'
    - '#64656a'
    - '#8b8996'
  brandStrength: 0.6875
  lightness: 0.7344773176591843
  saturation: 0.0579925044439733
  rhythmicContrast: 0.5
purpose: []
